### ISSUE TITLE
请问这个项目会持续吗？

### ISSUE THREAD

**Issue by gebilove** [WuZixing/OpenGeo3D#1]
我最近一直在找一个开源的三维地质建模库，看到这个项目还是很兴奋的。但是现在浏览了一下，只有qt的主窗口上传了。所以好奇想这个项目还会更新吗。

**Comment by WuZixing** [comment]
谢谢关注。项目刚开始，会持续下去的。近期计划先搭个框架，然后补充包括项目规划在内的文档资料，最后再继续完善具体功能。

**Comment by WuZixing** [comment]
> 
> 
> 我最近一直在找一个开源的三维地质建模库，看到这个项目还是很兴奋的。但是现在浏览了一下，只有qt的主窗口上传了。所以好奇想这个项目还会更新吗。

谢谢关注。项目刚开始，会持续下去的。近期计划先搭个框架，然后补充包括项目规划在内的文档资料，最后再继续完善具体功能。欢迎多多交流。:)

**Comment by gebilove** [comment]
> > 我最近一直在找一个开源的三维地质建模库，看到这个项目还是很兴奋的。但是现在浏览了一下，只有qt的主窗口上传了。所以好奇想这个项目还会更新吗。
> 
> 谢谢关注。项目刚开始，会持续下去的。近期计划先搭个框架，然后补充包括项目规划在内的文档资料，最后再继续完善具体功能。欢迎多多交流。:)

之前以为项目要正式开始，还要等很久，今天突然发现这个项目又更新了，很开心。其实我也在进行开源三维地质建模软件的研发，之前做了简单的基于钻孔的多层dem建模，基于钻孔的GTP建模，然后最近在做测井实时轨迹的研发。希望有机会能和您多多交流。

**Comment by gebilove** [comment]
> > > 我最近一直在找一个开源的三维地质建模库，看到这个项目还是很兴奋的。但是现在浏览了一下，只有qt的主窗口上传了。所以好奇想这个项目还会更新吗。
> > 
> > 
> > 谢谢关注。项目刚开始，会持续下去的。近期计划先搭个框架，然后补充包括项目规划在内的文档资料，最后再继续完善具体功能。欢迎多多交流。:)
> 
> 之前以为项目要正式开始，还要等很久，今天突然发现这个项目又更新了，很开心。其实我也在进行开源三维地质建模软件的研发，之前做了简单的基于钻孔的多层dem建模，基于钻孔的GTP建模，然后最近在做测井实时轨迹的研发。希望有机会能和您多多交流。

忘记补充了，我也是用VTK作为绘图库，然后结合Qt，用c++进行开发。

**Comment by WuZixing** [comment]
> 
> 之前以为项目要正式开始，还要等很久，今天突然发现这个项目又更新了，很开心。其实我也在进行开源三维地质建模软件的研发，之前做了简单的基于钻孔的多层dem建模，基于钻孔的GTP建模，然后最近在做测井实时轨迹的研发。希望有机会能和您多多交流。

👍 我的想法是直接用地质统计学和机器学习的有关方法来建模，有一点探索、学习的性质。后来我弃用Qt了，改用了自己熟悉的wxWidgets来做界面。一起加油！
