### ISSUE TITLE
读取XML文件只支持XML，不支持XML DOM格式

### ISSUE THREAD

**Issue by VegetableWithChicken** [WuZixing/OpenGeo3D#11]
#### Env
1. vtk:9.2
2. window X64

#### question
1.  isOK=false  Unsupportted encoding 
#### 其它解决方案
> 将encoding修改为 ANSCII，UTF-8,ISO----,等都读取失败，最后通过VSCode打开，发现是XML For DOM的格式

**Comment by WuZixing** [comment]
Geo3DML-CPP支持UTF-8编码的XML文件，不支持GB2312等其它编码。ASCII、GB2312、UTF-8等等都是文本文件的编码方式。但是XML For DOM不是这个概念，DOM是文档对象模型，是解析XML、HTML等文件的一种编程模型。跟它相对的是SAX。
