### ISSUE TITLE
您好，希望寻求向您进一步学习与交流的机会。

### ISSUE THREAD

**Issue by gebilove** [WuZixing/OpenGeo3D#2]
您好，我是一名中科院新疆生态与地理研究所的地球探测与信息技术专业的研二硕士，现在的课题是三维地质建模软件的研发。技术路线是基于钻孔的地层结构建模和剖面的矿体结构建模，以及使用八叉树对结构模型进行网格剖分建立属性模型。我已经跌跌撞撞的做了一些功能：如简单结构的地层建模，基于wits的实时钻井轨迹显示等。

我没有这种大型系统的设计经验，所以对于整个系统也缺乏设计；过去我一直依靠自己定义的数据结构作为基础，但是我逐渐发现了一些问题，比如我都无法定义自己的project类，难以设计变量的生命周期。所以我最近想采用Geo3DML作为系统的基础数据结构，也参考了您项目中的使用方法，收获很多。但是因为我能力有限，还是觉得难以下手使用。我观察到您是OpenGeo3D项目中的唯一作者，您也写了各阶段的开发计划，您一定有很多设计系统的经验值得我学习；我仔细看了您的代码，也觉得代码很规范。

所以我希望获取您的邮件或其他联系方式，以便能向您更好的学习。您如果在issues中回复联系方式不方便，我的邮件是gebi1994@126.com。真切的希望得到您的回复。

**Comment by WuZixing** [comment]
你好，我的邮箱 wzixing@qq.com ，欢迎交流
